CREATE USER pooladmin WITH PASSWORD 'CoolPool123';
CREATE DATABASE smartpool;

GRANT ALL PRIVILEGES ON DATABASE smartpool TO pooladmin;

\c smartpool;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO pooladmin;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO pooladmin;