version: '3.8'
services:
  postgres:
    image: postgres:14
    env_file:
      - ./.env
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
volumes:
  postgres-data:
